/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModeloVeiculo;
import model.Veiculo;
import service.ChamarQuandoSelecionar;

/**
 *
 * @author elena
 */
public class CadastroVeiculo extends javax.swing.JFrame {

    public int codigo_veiculo = 0;

    /**
     * Creates new form CadastroVeiculo
     */
    public CadastroVeiculo() {
        initComponents();
        service.CadastroVeiculo cad = new service.CadastroVeiculo();
        cad.ListaVeiculo(jTextFieldDescricao.getText(), (DefaultTableModel) jTabelaVeiculos.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void limparCampos() {
        jTextFieldDescricao.setText("");
        jTextFieldPlaca1.setText("");
        // jComboBoxModelo.setComponentOrientation("");
        jTextFieldPessoa.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTipoPessoa = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldPessoa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaVeiculos = new javax.swing.JTable();
        jTextFieldPlaca1 = new javax.swing.JTextField();
        jComboBoxModelo = new javax.swing.JComboBox<>();
        jToggleButtonPessoa = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLista = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(117, 117, 123));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 740, 60));

        jLabelTipoPessoa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTipoPessoa.setForeground(new java.awt.Color(204, 0, 51));
        jLabelTipoPessoa.setText("Cadastro");
        jPanel2.add(jLabelTipoPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jButtonFechar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 100, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Modelo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jPanel4.setBackground(new java.awt.Color(29, 31, 39));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\elena\\Desktop\\a\\Listrinhas.png")); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\elena\\Desktop\\a\\Configurações.png")); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\elena\\Desktop\\a\\Informação.png")); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 50, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 510));

        jButtonExcluir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 89, -1));

        jButtonSalvar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 89, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Localizar");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(29, 31, 39));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 660, 20));

        jButtonAlterar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 89, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Descrição ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Placa");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Pessoa");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        jPanel2.add(jTextFieldDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 220, -1));

        jTextFieldPessoa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTextFieldPessoaAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jTextFieldPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 410, -1));

        jTabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Descrição", "Placa", "Modelo", "Pessoa"
            }
        ));
        jScrollPane1.setViewportView(jTabelaVeiculos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 700, 120));
        jPanel2.add(jTextFieldPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 130, -1));

        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeloActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 220, -1));

        jToggleButtonPessoa.setText("...");
        jToggleButtonPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPessoaActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButtonPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 70, -1));

        jLabel1.setText("Listar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jTextFieldLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldListaActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 590, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        service.CadastroVeiculo cad = new service.CadastroVeiculo();
        String descricao = jTextFieldDescricao.getText();
        String placa = jTextFieldPlaca1.getText();
        ModeloVeiculo modelo = (ModeloVeiculo) jComboBoxModelo.getSelectedItem();
        String modeloId = String.valueOf(modelo.getIdmodeloveiculo());
        String pessoa = jTextFieldPessoa.getText();
        //combo da marca 
        //Botão para pegar a pessoa 
        if (descricao == "") {
            JOptionPane.showMessageDialog(this, "Preencher o campo descrição !");
        } else if (placa == null) {
            JOptionPane.showMessageDialog(this, "Preencher o campo placa!");
        }
        if (codigo_veiculo == 0) {
            cad.salvarCadVeiculo(descricao, placa, modeloId, pessoa);
        } else {
            cad.AlterarCadVeiculo(descricao, placa, modeloId, pessoa, codigo_veiculo);
            jButtonAlterar.setEnabled(true);
        }
        codigo_veiculo = 0;
        limparCampos();
        cad.ListaVeiculo(jTextFieldDescricao.getText(), (DefaultTableModel) jTabelaVeiculos.getModel());


    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        int linha = jTabelaVeiculos.getSelectedRow();
        if (linha >= 0) {
            int id = Integer.parseInt(jTabelaVeiculos.getValueAt(linha, 0).toString());
            service.CadastroVeiculo cad = new service.CadastroVeiculo();
            Veiculo veiculo = cad.buscaPorId(id);

            codigo_veiculo = id;
            jTextFieldDescricao.setText(veiculo.getNomemodelo());
            jTextFieldPlaca1.setText(veiculo.getPlacaveiculo());
            jComboBoxModelo.setSelectedItem(veiculo.getModelo());
            jTextFieldPessoa.setText(String.valueOf(veiculo.getPessoa().getId()));

            jButtonAlterar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha da tabela!");
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldPessoaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextFieldPessoaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPessoaAncestorMoved

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if (JOptionPane.showConfirmDialog(this, "Você está certo disso?")
                == JOptionPane.YES_OPTION) {
            int linha = jTabelaVeiculos.getSelectedRow();
            if (linha >= 0) {
                int codigo = Integer.parseInt(
                        String.valueOf(jTabelaVeiculos.getValueAt(linha, 0))
                );
                service.CadastroVeiculo cad = new service.CadastroVeiculo();
                cad.deletarCadVeiculo(codigo);
                cad.ListaVeiculo(jTextFieldDescricao.getText(), (DefaultTableModel) jTabelaVeiculos.getModel());
                limparCampos();
                jButtonAlterar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma linha!");
            }
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldListaActionPerformed
        service.CadastroVeiculo cad = new service.CadastroVeiculo();
        cad.ListaVeiculo(jTextFieldDescricao.getText(), (DefaultTableModel) jTabelaVeiculos.getModel());


    }//GEN-LAST:event_jTextFieldListaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        service.CadastroVeiculo cad = new service.CadastroVeiculo();
        List<ModeloVeiculo> listaVeiculo = cad.listaModelos();
        DefaultComboBoxModel model = new DefaultComboBoxModel<>(listaVeiculo.toArray());
        jComboBoxModelo.setModel(model);

    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxModeloActionPerformed

    private void jToggleButtonPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPessoaActionPerformed
        CadastroPessoa form = new CadastroPessoa(new ChamarQuandoSelecionar() {
            @Override
            public void ReceberValor(int id) {
                jTextFieldPessoa.setText(String.valueOf(id));
            }
        });
        form.setVisible(true);
    }//GEN-LAST:event_jToggleButtonPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTipoPessoa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTabelaVeiculos;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldLista;
    private javax.swing.JTextField jTextFieldPessoa;
    private javax.swing.JTextField jTextFieldPlaca1;
    private javax.swing.JToggleButton jToggleButtonPessoa;
    // End of variables declaration//GEN-END:variables

}
