/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.ChamarQuandoSelecionar;

/**
 *
 * @author elena
 */
public class CadastroPessoa extends javax.swing.JFrame {

    public int codigo_pessoa = 0;
    private ChamarQuandoSelecionar eventoChamaSeleciona;

    /**
     * Creates new form CadastroPessoa
     */
    public CadastroPessoa() {
        initComponents();
        service.CadastroPessoa cad = new service.CadastroPessoa();
        jButtonSelecionar.setVisible(false);
        cad.ListaPessoa("", (DefaultTableModel) jTableTabela.getModel());
    }

    public CadastroPessoa(ChamarQuandoSelecionar chamarSelecionar) {
        this();
        jButtonSelecionar.setVisible(true);
        this.eventoChamaSeleciona = chamarSelecionar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonJuridica = new javax.swing.JRadioButton();
        jRadioButtonFisica = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabela = new javax.swing.JTable();
        jButtonSelecionar = new javax.swing.JButton();
        jPasswordSenha = new javax.swing.JPasswordField();
        jTextFieldDocumento = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTipoPessoa1 = new javax.swing.JLabel();
        jButtonExcluir1 = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonFechar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBPesquisar = new javax.swing.JButton();
        jTDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelTipoPessoa = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setName("CadastroPessoa"); // NOI18N
        setPreferredSize(new java.awt.Dimension(910, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButtonJuridica.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jRadioButtonJuridica.setText("Juridica");
        jPanel2.add(jRadioButtonJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, -1, -1));

        jRadioButtonFisica.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jRadioButtonFisica.setText("Física");
        jRadioButtonFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFisicaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 70, -1));

        jTableTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Tipo Pessoa", "Documento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTabela);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 860, 90));

        jButtonSelecionar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 100, 30));
        jPanel2.add(jPasswordSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 170, -1));
        jPanel2.add(jTextFieldDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 510, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Nome ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Documento");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Senha");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabelTipoPessoa1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTipoPessoa1.setText("Tipo pessoa");
        jPanel2.add(jLabelTipoPessoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        jButtonExcluir1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonExcluir1.setText("Excluir");
        jButtonExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluir1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 89, -1));

        jButtonSalvar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 89, -1));

        jButtonAlterar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 89, -1));

        jButtonFechar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonFechar1.setText("Fechar");
        jButtonFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonFechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 100, 30));

        jPanel3.setBackground(new java.awt.Color(51, 110, 123));

        jBPesquisar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBPesquisar.setForeground(new java.awt.Color(51, 51, 51));
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jTDescricao.setCaretColor(new java.awt.Color(255, 255, 255));
        jTDescricao.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescricaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Consulta de pessoas:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPesquisar)
                    .addComponent(jTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 50));

        jLabelTipoPessoa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTipoPessoa.setForeground(new java.awt.Color(51, 110, 123));
        jLabelTipoPessoa.setText("Cadastro de Pessoas");
        jPanel2.add(jLabelTipoPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFisicaActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    public void limparCampos() {
        jTextFieldNome.setText("");
        jTextFieldDocumento.setText("");
        jPasswordSenha.setText("");
        jRadioButtonFisica.setSelected(false);
        jRadioButtonJuridica.setSelected(false);

    }

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        service.CadastroPessoa cad = new service.CadastroPessoa();
        String nome = jTextFieldNome.getText();
        String documento = jTextFieldDocumento.getText();
        String tipopessoa = "";
        if (!jRadioButtonFisica.isSelected()) {
            tipopessoa = "1"; //pessoa juridica
        } else {
            tipopessoa = "2"; //pessoa fisica
        }

        String senha = jPasswordSenha.getText();

        if (nome == "") {
            JOptionPane.showMessageDialog(this, "Preencher o campo nome!");
        } else if (tipopessoa == "") {
            JOptionPane.showMessageDialog(this, "Preencher o tipo de pessoa");
        } else if (documento == "") {
            JOptionPane.showMessageDialog(this, "Preencher o campo documento!");
        }
        if (codigo_pessoa == 0) {
            cad.salvarCadPessoa(nome, documento, tipopessoa, senha);
        } else {
            cad.alterarCadPessoa(nome, documento, tipopessoa, senha, codigo_pessoa);
            codigo_pessoa = 0;
            jButtonAlterar.setEnabled(true);
        }
        limparCampos();
        cad.ListaPessoa("", (DefaultTableModel) jTableTabela.getModel());


    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        int linha = jTableTabela.getSelectedRow();
        if (linha >= 0) {
            String codigo = String.valueOf(jTableTabela.getValueAt(linha, 0));
            String nome = String.valueOf(jTableTabela.getValueAt(linha, 1));
            String tipopessoa = String.valueOf(jTableTabela.getValueAt(linha, 2));
            String documento = String.valueOf(jTableTabela.getValueAt(linha, 3));

            codigo_pessoa = Integer.parseInt(codigo);

            jTextFieldNome.setText(nome);

            if (tipopessoa == "1") {//pessoa juridica
                jRadioButtonJuridica.setSelected(true);
            } else {
                jRadioButtonFisica.setSelected(true);
            }
            jTextFieldDocumento.setText(documento);
            jButtonAlterar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha da tabela!");
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluir1ActionPerformed

        if (JOptionPane.showConfirmDialog(this, "Você tem certeza disso ?")
                == JOptionPane.YES_OPTION) {
            int linha = jTableTabela.getSelectedRow();
            if (linha >= 0) {
                int codigo = Integer.parseInt(
                        String.valueOf(jTableTabela.getValueAt(linha, 0))
                );
                service.CadastroPessoa cad = new service.CadastroPessoa();
                cad.deletarCadPessoa(codigo);
                cad.ListaPessoa(jTextFieldDocumento.getText(), (DefaultTableModel) jTableTabela.getModel());
                limparCampos();
                jButtonAlterar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma linha!");
            }
        }

    }//GEN-LAST:event_jButtonExcluir1ActionPerformed

    private void jButtonFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechar1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFechar1ActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        int linha = jTableTabela.getSelectedRow();
        if (linha >= 0) {
            int codigo = Integer.parseInt(
                    String.valueOf(jTableTabela.getValueAt(linha, 0))
            );
            eventoChamaSeleciona.ReceberValor(codigo);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        service.CadastroPecas cad = new service.CadastroPecas();
        cad.ListaPecas(jTDescricao.getText(), (DefaultTableModel)jTableTabela.getModel());
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jTDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDescricaoActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir1;
    private javax.swing.JButton jButtonFechar1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTipoPessoa;
    private javax.swing.JLabel jLabelTipoPessoa1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JRadioButton jRadioButtonFisica;
    private javax.swing.JRadioButton jRadioButtonJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDescricao;
    private javax.swing.JTable jTableTabela;
    private javax.swing.JTextField jTextFieldDocumento;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
