/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author elena
 */
public class ConsultaHistoricoVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaHistoricoVeiculo
     */
    public ConsultaHistoricoVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButtonVeiculo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldVeiculo = new javax.swing.JTextField();
        jButtonVeiculo1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldVeiculo1 = new javax.swing.JTextField();
        jButtonVeiculo2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldVeiculo2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonTipoServico1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonImprimirOrdem = new javax.swing.JButton();
        jButtonVeiculo3 = new javax.swing.JButton();
        jButtonVeiculo4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 110, 123));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Histórico Veículo / Pessoa ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Data inicial ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jFormattedTextField1.setText("    /   /   ");
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 110, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Data final");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 20));

        jFormattedTextField2.setText("    /   /   ");
        jPanel1.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 110, 20));

        jButtonVeiculo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonVeiculo.setText("Buscar");
        jPanel1.add(jButtonVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, 20));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Veículo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel1.add(jTextFieldVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, -1));

        jButtonVeiculo1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonVeiculo1.setText("Buscar");
        jPanel1.add(jButtonVeiculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 80, 20));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Pessoas");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel1.add(jTextFieldVeiculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, -1));

        jButtonVeiculo2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonVeiculo2.setText("Imprimir");
        jPanel1.add(jButtonVeiculo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 120, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Produtos");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, -1));
        jPanel1.add(jTextFieldVeiculo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 120, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Tipo de serviço");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jButtonTipoServico1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonTipoServico1.setText("Buscar");
        jPanel1.add(jButtonTipoServico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 90, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 120, -1));

        jButtonImprimirOrdem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonImprimirOrdem.setText("Imprimir Ordem");
        jPanel1.add(jButtonImprimirOrdem, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 170, -1));

        jButtonVeiculo3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonVeiculo3.setText("Buscar");
        jPanel1.add(jButtonVeiculo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 90, 20));

        jButtonVeiculo4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonVeiculo4.setText("Buscar");
        jPanel1.add(jButtonVeiculo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 120, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Data Entrada", "Veículo", "Pessoa", "Tipo de Serviço", "Produtos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 610, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 340));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaHistoricoVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImprimirOrdem;
    private javax.swing.JButton jButtonTipoServico1;
    private javax.swing.JButton jButtonVeiculo;
    private javax.swing.JButton jButtonVeiculo1;
    private javax.swing.JButton jButtonVeiculo2;
    private javax.swing.JButton jButtonVeiculo3;
    private javax.swing.JButton jButtonVeiculo4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldVeiculo;
    private javax.swing.JTextField jTextFieldVeiculo1;
    private javax.swing.JTextField jTextFieldVeiculo2;
    // End of variables declaration//GEN-END:variables
}
