/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author elena
 */
public class Lancamento extends javax.swing.JFrame {

    /**
     * Creates new form Lancamento
     */
    public Lancamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPessoa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTipoServico = new javax.swing.JTextField();
        jButtonVeiculo = new javax.swing.JButton();
        jRadioButtonJuridica = new javax.swing.JRadioButton();
        jRadioButtonFisica = new javax.swing.JRadioButton();
        jLabelTipoPessoa1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButtonGravar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonImprimirOrdem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTabela = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextFieldValorunitario = new javax.swing.JTextField();
        jButtonBuscaPessoa2 = new javax.swing.JButton();
        jTextFieldProduto1 = new javax.swing.JTextField();
        jTextFieldQuantidade1 = new javax.swing.JTextField();
        jButtonCancelar1 = new javax.swing.JButton();
        jButtonCancelar2 = new javax.swing.JButton();
        jButtonCancelar3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDocumento1 = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldVeiculo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPlaca1 = new javax.swing.JTextField();
        jButtonBuscarProduto1 = new javax.swing.JButton();
        jButtonTipoServico1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 110, 123));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dados pessoais ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(836, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Nome do Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(jTextFieldPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 410, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Documento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Itens da Ordem");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Data de entrada ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(jTextFieldTipoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 120, -1));

        jButtonVeiculo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonVeiculo.setText("Buscar");
        jPanel1.add(jButtonVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, 20));

        jRadioButtonJuridica.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jRadioButtonJuridica.setText("Juridica");
        jPanel1.add(jRadioButtonJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jRadioButtonFisica.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jRadioButtonFisica.setText("Física");
        jRadioButtonFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFisicaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 70, -1));

        jLabelTipoPessoa1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelTipoPessoa1.setText("Tipo pessoa");
        jPanel1.add(jLabelTipoPessoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jFormattedTextField1.setText("    /   /   ");
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, -1));

        jButtonGravar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonGravar.setText("Gravar");
        jPanel1.add(jButtonGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 120, -1));

        jButtonCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonCancelar.setText("Excluir");
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 80, -1));

        jButtonImprimirOrdem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonImprimirOrdem.setText("Imprimir Ordem");
        jPanel1.add(jButtonImprimirOrdem, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 170, -1));

        jTableTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Produto", "Descrição Produto", "Valor unitário", "Quantidade", "Valor total"
            }
        ));
        jScrollPane2.setViewportView(jTableTabela);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 920, 130));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Valor unitário");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Tipo de serviço");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Produto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Quantidade");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jTextFieldValorunitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 80, -1));

        jButtonBuscaPessoa2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonBuscaPessoa2.setText("Buscar");
        jPanel1.add(jButtonBuscaPessoa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 110, 20));
        jPanel1.add(jTextFieldProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 140, -1));
        jPanel1.add(jTextFieldQuantidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 80, -1));

        jButtonCancelar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonCancelar1.setText("Cancelar");
        jPanel1.add(jButtonCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 120, -1));

        jButtonCancelar2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonCancelar2.setText("Incluir");
        jPanel1.add(jButtonCancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 80, -1));

        jButtonCancelar3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonCancelar3.setText("Alterar");
        jPanel1.add(jButtonCancelar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 90, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Dados da Ordem de Serviço ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, 940, 0));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Placa");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));
        jPanel1.add(jTextFieldDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, -1));

        jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Veículo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(jTextFieldVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 70, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Modelo Veículo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(jTextFieldPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 170, -1));

        jButtonBuscarProduto1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonBuscarProduto1.setText("Buscar");
        jPanel1.add(jButtonBuscarProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, 20));

        jButtonTipoServico1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButtonTipoServico1.setText("Buscar");
        jPanel1.add(jButtonTipoServico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFisicaActionPerformed

    private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lancamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscaPessoa2;
    private javax.swing.JButton jButtonBuscarProduto1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonCancelar2;
    private javax.swing.JButton jButtonCancelar3;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonImprimirOrdem;
    private javax.swing.JButton jButtonTipoServico1;
    private javax.swing.JButton jButtonVeiculo;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTipoPessoa1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFisica;
    private javax.swing.JRadioButton jRadioButtonJuridica;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableTabela;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextFieldDocumento1;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPessoa;
    private javax.swing.JTextField jTextFieldPlaca1;
    private javax.swing.JTextField jTextFieldProduto1;
    private javax.swing.JTextField jTextFieldQuantidade1;
    private javax.swing.JTextField jTextFieldTipoServico;
    private javax.swing.JTextField jTextFieldValorunitario;
    private javax.swing.JTextField jTextFieldVeiculo;
    // End of variables declaration//GEN-END:variables
}
